### ISSUE TITLE
GraphResourceDictionary.xaml.CS file is missing !!

### ISSUE THREAD

**Issue by AymenDaoudi** [SamTheDev/PageRank-Analyzer#1]
Seems that the file **"GraphResourceDictionary.xaml.CS"** at **"\PageRank-Analyzer-master\PageRank-Analyzer-master\LuceneSearchClient\Resources"** is missing !

**Comment by SamTh3D3v** [comment]
fixed

**Comment by AymenDaoudi** [comment]
Thanks
